// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8C4KKyHlyzYJz3E-Bz9_6TU-TdcSDpp8',
    appId: '1:331010575336:web:3deb6125347f092e82725d',
    messagingSenderId: '331010575336',
    projectId: 'flutter-circle-app',
    authDomain: 'flutter-circle-app.firebaseapp.com',
    storageBucket: 'flutter-circle-app.appspot.com',
    measurementId: 'G-MQ9LM010Y5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9j0dkCWN0g2h5XL48yUWWstw-RxLskcQ',
    appId: '1:331010575336:android:fdf32bc2730c682d82725d',
    messagingSenderId: '331010575336',
    projectId: 'flutter-circle-app',
    storageBucket: 'flutter-circle-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaAHwzr-efDqJ3C7mISeDqI9ErgjJLfXI',
    appId: '1:331010575336:ios:6546468ed964d28582725d',
    messagingSenderId: '331010575336',
    projectId: 'flutter-circle-app',
    storageBucket: 'flutter-circle-app.appspot.com',
    androidClientId: '331010575336-2drtsdj3esoj0eaiulpcg0gk5qac2491.apps.googleusercontent.com',
    iosClientId: '331010575336-gf0scqslujcis52c3joaehep96n4933n.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAppCircle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaAHwzr-efDqJ3C7mISeDqI9ErgjJLfXI',
    appId: '1:331010575336:ios:6546468ed964d28582725d',
    messagingSenderId: '331010575336',
    projectId: 'flutter-circle-app',
    storageBucket: 'flutter-circle-app.appspot.com',
    androidClientId: '331010575336-2drtsdj3esoj0eaiulpcg0gk5qac2491.apps.googleusercontent.com',
    iosClientId: '331010575336-gf0scqslujcis52c3joaehep96n4933n.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAppCircle',
  );
}
